version: '3.7'
services:
    caddy:
        build:
            context: ./docker/caddy
        ports:
            - "80:80"
            - "443:443"
        volumes:
            - ./:/var/www/symfony:cached
            - ./docker/logs/caddy:/var/log/caddy

    db:
        image: mysql:8.0
        ports:
            - "3306:3306"
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: symfony
            MYSQL_USER: symfony
            MYSQL_PASSWORD: symfony
        command: mysqld --default-authentication-plugin=mysql_native_password --sql_mode=""

    fpm:
        build:
            context: ./docker/php-fpm
        volumes:
            - ./:/var/www/symfony:cached
        depends_on:
            - caddy
            - db